// <auto-generated />
using System;
using LaboratorioVacinas.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaboratorioVacinas.Migrations
{
    [DbContext(typeof(LaboratorioVacinasContext))]
    partial class LaboratorioVacinasContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("LaboratorioVacinas.Models.Vacina", b =>
                {
                    b.Property<int>("VacinaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("DataCriacao")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("FkVirus")
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .HasColumnType("longtext");

                    b.HasKey("VacinaId");

                    b.HasIndex("FkVirus");

                    b.ToTable("Vacina");
                });

            modelBuilder.Entity("LaboratorioVacinas.Models.Virus", b =>
                {
                    b.Property<int>("VirusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("TemVacina")
                        .HasColumnType("tinyint(1)");

                    b.HasKey("VirusId");

                    b.ToTable("Virus");
                });

            modelBuilder.Entity("LaboratorioVacinas.Models.Vacina", b =>
                {
                    b.HasOne("LaboratorioVacinas.Models.Virus", "Virus")
                        .WithMany("Vacinas")
                        .HasForeignKey("FkVirus")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Virus");
                });

            modelBuilder.Entity("LaboratorioVacinas.Models.Virus", b =>
                {
                    b.Navigation("Vacinas");
                });
#pragma warning restore 612, 618
        }
    }
}
